//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selfies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class block
    {
        public int id { get; set; }
        public int blockedHandleId { get; set; }
        public int blockedByHandleId { get; set; }
        public System.DateTime blockedOn { get; set; }
        public int active { get; set; }
    
        public virtual handle blockedByHandle { get; set; }
        public virtual handle blockedHandle { get; set; }
    }
}
