//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selfies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class follower
    {
        public int id { get; set; }
        public int followerId { get; set; }
        public int followeeId { get; set; }
        public int active { get; set; }
    
        public virtual handle followeeHandle { get; set; }
        public virtual handle followerHandle { get; set; }
    }
}
