//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selfies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public int fromHandleId { get; set; }
        public int threadId { get; set; }
        public System.DateTime sentDate { get; set; }
        public int active { get; set; }
        public int anon { get; set; }
        public int toHandleSeen { get; set; }
        public string messageText { get; set; }
    
        public virtual handle handle { get; set; }
        public virtual thread thread { get; set; }
    }
}
