//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selfies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public string fromHandleId { get; set; }
        public string message1 { get; set; }
        public string selfieId { get; set; }
        public Nullable<System.DateTime> sentDate { get; set; }
    }
}
