//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selfies.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class selfiesMySQL : DbContext
    {
        public selfiesMySQL()
            : base("name=selfiesMySQL")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<selfy> selfies { get; set; }
        public DbSet<handle> handles { get; set; }
        public DbSet<follower> followers { get; set; }
        public DbSet<thread> threads { get; set; }
    }
}
