//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selfies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class selfy
    {
        public int id { get; set; }
        public string userGuid { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string selfieGuid { get; set; }
    }
}
