//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace selfies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thread
    {
        public thread()
        {
            this.messages = new HashSet<message>();
        }
    
        public int id { get; set; }
        public int fromHandleId { get; set; }
        public int toHandleId { get; set; }
        public string groupKey { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public int active { get; set; }
        public string caption { get; set; }
        public Nullable<int> authorizeRequest { get; set; }
        public Nullable<int> toHandleSeen { get; set; }
        public Nullable<int> hearts { get; set; }
        public int uploadSuccess { get; set; }
        public string location { get; set; }
        public string font { get; set; }
        public string textColor { get; set; }
    
        public virtual handle fromHandle { get; set; }
        public virtual handle toHandle { get; set; }
        public virtual ICollection<message> messages { get; set; }
    }
}
